import Bun from "bun";
import forge from "node-forge";

export async function generateKeyPair() {

	// Check if .env file exists
	if (!Bun.file(".env.local").exists()) { throw new Error("No .env.local file found"); }

	const keypair = forge.pki.rsa.generateKeyPair(4096);
	const keys = {
		publicKey: forge.pki.publicKeyToPem(keypair.publicKey),
		privateKey: forge.pki.privateKeyToPem(keypair.privateKey)
	}

	// Sanity check to make sure the keys are not already in the file
	const env = await Bun.file(".env.local").text();
	if (env.includes("FEDERATION_PUBLIC_KEY") && env.includes("FEDERATION_PRIVATE_KEY")) {
		throw new Error("Keys already exist in .env.local file, if you wish to regenerate them, please delete the keys and run the command again");
	}

	// Read the .env.local file and append the keys to the file without overwriting the existing keys
	// Escape newlines for .env format (single-line value that expands to PEM when loaded)
	const publicKey = keys.publicKey.replace(/\r?\n/g, "\\n");
	const privateKey = keys.privateKey.replace(/\r?\n/g, "\\n");
	const separator = "#------------- SERVER KEYS -------------\n# DO NOT EDIT THIS SECTION, THIS IS AUTOMATICALLY GENERATED BY THE SERVER\nDO NOT PUBLISH THE PRIVATE KEY TO THE PUBLIC!";
	await Bun.write(".env.local", `${env}\n\n${separator}\n\nFEDERATION_PUBLIC_KEY="${publicKey}"\nFEDERATION_PRIVATE_KEY="${privateKey}"`);

	console.log("Keys generated successfully");
	return keys;
}

generateKeyPair();