// app/layout.tsx
import type {Metadata} from "next";
import "./globals.css";
import {Public_Sans} from 'next/font/google';
import {UserProvider} from "@/contexts/user";
import Sidebar from "@/components/main/sidebar/sidebar";
import {getAuthenticatedUser} from "@/lib/auth";
import {SharedStateProvider} from "@/hooks/shared-states";
import {ThemeProvider} from "next-themes";

const publicSans = Public_Sans({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-public-sans'
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	                                         children,
                                         }: {
	children: React.ReactNode & { props?: { childProp?: { segment?: string } } };
}) {
	const initialUser = await getAuthenticatedUser();
	const isAuthPage = (children as any)?.props?.childProp?.segment === 'auth';
	
	// Auth layout
	if (isAuthPage) {
		return (
			<html lang="en">
			<body className={`${publicSans.variable} font-sans antialiased`}>
			<ThemeProvider
				attribute="class"
				defaultTheme="system"
				enableSystem
			>
				<UserProvider initialUser={initialUser}>
					<main className="min-h-screen flex items-center justify-center">
						{children}
					</main>
				</UserProvider>
			</ThemeProvider>
			</body>
			</html>
		);
	}
	
	// Main layout
	return (
		<html lang="en">
		<body className={`${publicSans.variable} font-sans antialiased`}>
		<ThemeProvider
			attribute="class"
			defaultTheme="system"
			enableSystem
		>
			<UserProvider initialUser={initialUser}>
				<SharedStateProvider>
					<div className={`max-h-[1080px] p-6 bg-secondary`}>
						<div className="flex bg-background">
							<Sidebar>
								{children}
							</Sidebar>
						</div>
					</div>
				</SharedStateProvider>
			</UserProvider>
		</ThemeProvider>
		</body>
		</html>
	);
}